services:
  base:
    build:
      context: ./thirdparty/garrysmod-docker
      dockerfile: ubuntu.Dockerfile
    image: gmodds-base

  gmodds-runtime:
    build:
      context: .
      dockerfile: Dockerfile
    image: gmodds-atomic
    container_name: gmodds-atomic-runtime
    depends_on:
      - base
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"